/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsAndConditionsRouteImport } from './routes/terms-and-conditions'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BlogIndexRouteImport } from './routes/blog/index'
import { Route as BlogWhatToAskCustomersBeforeTattooSessionRouteImport } from './routes/blog/what-to-ask-customers-before-tattoo-session'
import { Route as BlogHowToAppearProfessionalToTattooClientsRouteImport } from './routes/blog/how-to-appear-professional-to-tattoo-clients'

const TermsAndConditionsRoute = TermsAndConditionsRouteImport.update({
  id: '/terms-and-conditions',
  path: '/terms-and-conditions',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogWhatToAskCustomersBeforeTattooSessionRoute =
  BlogWhatToAskCustomersBeforeTattooSessionRouteImport.update({
    id: '/blog/what-to-ask-customers-before-tattoo-session',
    path: '/blog/what-to-ask-customers-before-tattoo-session',
    getParentRoute: () => rootRouteImport,
  } as any)
const BlogHowToAppearProfessionalToTattooClientsRoute =
  BlogHowToAppearProfessionalToTattooClientsRouteImport.update({
    id: '/blog/how-to-appear-professional-to-tattoo-clients',
    path: '/blog/how-to-appear-professional-to-tattoo-clients',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/blog/how-to-appear-professional-to-tattoo-clients': typeof BlogHowToAppearProfessionalToTattooClientsRoute
  '/blog/what-to-ask-customers-before-tattoo-session': typeof BlogWhatToAskCustomersBeforeTattooSessionRoute
  '/blog/': typeof BlogIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/blog/how-to-appear-professional-to-tattoo-clients': typeof BlogHowToAppearProfessionalToTattooClientsRoute
  '/blog/what-to-ask-customers-before-tattoo-session': typeof BlogWhatToAskCustomersBeforeTattooSessionRoute
  '/blog': typeof BlogIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/blog/how-to-appear-professional-to-tattoo-clients': typeof BlogHowToAppearProfessionalToTattooClientsRoute
  '/blog/what-to-ask-customers-before-tattoo-session': typeof BlogWhatToAskCustomersBeforeTattooSessionRoute
  '/blog/': typeof BlogIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/privacy-policy'
    | '/sitemap.xml'
    | '/terms-and-conditions'
    | '/blog/how-to-appear-professional-to-tattoo-clients'
    | '/blog/what-to-ask-customers-before-tattoo-session'
    | '/blog/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/privacy-policy'
    | '/sitemap.xml'
    | '/terms-and-conditions'
    | '/blog/how-to-appear-professional-to-tattoo-clients'
    | '/blog/what-to-ask-customers-before-tattoo-session'
    | '/blog'
  id:
    | '__root__'
    | '/'
    | '/privacy-policy'
    | '/sitemap.xml'
    | '/terms-and-conditions'
    | '/blog/how-to-appear-professional-to-tattoo-clients'
    | '/blog/what-to-ask-customers-before-tattoo-session'
    | '/blog/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsAndConditionsRoute: typeof TermsAndConditionsRoute
  BlogHowToAppearProfessionalToTattooClientsRoute: typeof BlogHowToAppearProfessionalToTattooClientsRoute
  BlogWhatToAskCustomersBeforeTattooSessionRoute: typeof BlogWhatToAskCustomersBeforeTattooSessionRoute
  BlogIndexRoute: typeof BlogIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms-and-conditions': {
      id: '/terms-and-conditions'
      path: '/terms-and-conditions'
      fullPath: '/terms-and-conditions'
      preLoaderRoute: typeof TermsAndConditionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/what-to-ask-customers-before-tattoo-session': {
      id: '/blog/what-to-ask-customers-before-tattoo-session'
      path: '/blog/what-to-ask-customers-before-tattoo-session'
      fullPath: '/blog/what-to-ask-customers-before-tattoo-session'
      preLoaderRoute: typeof BlogWhatToAskCustomersBeforeTattooSessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/how-to-appear-professional-to-tattoo-clients': {
      id: '/blog/how-to-appear-professional-to-tattoo-clients'
      path: '/blog/how-to-appear-professional-to-tattoo-clients'
      fullPath: '/blog/how-to-appear-professional-to-tattoo-clients'
      preLoaderRoute: typeof BlogHowToAppearProfessionalToTattooClientsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsAndConditionsRoute: TermsAndConditionsRoute,
  BlogHowToAppearProfessionalToTattooClientsRoute:
    BlogHowToAppearProfessionalToTattooClientsRoute,
  BlogWhatToAskCustomersBeforeTattooSessionRoute:
    BlogWhatToAskCustomersBeforeTattooSessionRoute,
  BlogIndexRoute: BlogIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
